social-plan-it/plan-it-social-web

app/components/links.tsx

Build first version of reusable `Link` UI component inside the new `component` folder.
We want to create reusable components (DRY) for better developer productivity. The first version of the `Link` component is meant as a starting point to then add more styles and logic to it.
One issue with UI components is the desire to demand UI styles following the design system while allowing extensibility to fit layout and customization requirements.
We looked into different ways to implement this component. Such as merging class names together in one string, but we decided that this is too difficult to reason with which classes would take effect.
One possible solution is implemented in this PR which adds a wrapping `div` which can be styled by the component consumer. This allows us to prevent folks …

implement first version of link ui component

---

.github/pull_request_template

Update pull request template
The PR template is used to provide guidance and structure for PR descriptions. As a template, it should only include information that a developer has to fill out. Any other additional information creates boilerplate code that one has to remove when creating a new PR. These small changes remove the boilerplate information or turn them into HTML comments (so they are hidden from the reader of the PR description).

Update pull request template

---

package-lock.json
package.json

Issue: #18
This PR adds [Headless UI](https://headlessui.com/react) to the npm dependencies.
A component library builds out accessible and state-of-the-art UI components. We want to use a component library to avoid re-inventing the wheel and maintaining fundamental UI components ourselves.
Headless UI is a component library maintained and developed by the team behind Tailwind CSS. Since we already use Tailwind, picking Headless UI should integrate nicely with our existing stack.
Linkt o Headless UI components list: https://headlessui.com/
Challenges and discussion can be found in the associated ticket #18.
Screenshot of Headless UI Toggle and Tabs used Social Plan-it:

Install Headless UI (component library)

---

package-lock.json
prisma/schema.prisma

Summary (1-2 sentences)
I want to break up this issue into many smaller sub issues so this will be my first sub issue for issue https://github.com/social-plan-it/plan-it-social-web/issues/32
Details (reason and description of the changes)
I thought the best way to start was to create the models
Challenges (what problems did I face?) (optional)
Deciding if the model relationship was going to be many-to-many or one-to-many.
Alternative implementations (what alternatives were considered and why were they disregarded?) (optional)
First thought it was going to be many-to-many then decided it was one-to-many.
Solution (how did I fix the problems?) (optional)
N/A
Sources (links that helped to resolve these challenges.) (optional)
https://www.prisma.io/docs/concepts/components/prisma-schema/relati …

Add Event and Group database models

---

app/components/top-nav.tsx
app/hooks/useCurrentUser.ts
app/modules/session/session.server.ts
app/root.tsx
app/routes/logout.tsx

Issue: #26 
Implement logout functionality and remove hardcoded `SESSION_SECRET`
- Created new `getCurrentUser` function in `session.server.ts` to retrieve current logged in user from db
- Created new `logout` function in `session.server.ts` to log user out by destroying the session cookie
- Created new `/logout` route to conveniently invoke the `logout` function
- Load current user data as an object in the app's root in order to show user logged in state in UI
- Created new `useCurrentUser` hook to quickly retrieve current user object in components
- Updated `TopNav` component to reflect user logged in state
- Removed previously hardcoded `SESSION_SECRET` in `session.server.ts`. The secret is now loaded from the `.env` file in order to prevent it from being exposed publicly.
I was …

Add logout functionality and remove hardcoded SESSION_SECRET

---

app/routes/group.new.tsx
app/routes/group.tsx
app/routes/group/new.tsx

Issue: #<Number> 32.2 (Issue 32 broken down even further)
Created the UI page to create a new group
The UI styling (CSS) is not very good. Perhaps we can go over it in a meeting to improve the tailwind code.
I don't have a very good understanding of styling (CSS)
I simply implemented the UI to the best of my knowledge
Not fixed. UI looks ugly (highly unformatted)
N/A at this time

Codemech/issue#32.2 - New group creation page UI

---

CONTRIBUTING.md

Issue: #45
Added some quick hints on how to get started with our project.
This is mainly to help me remember steps for my next PR ;)
Thank you Kent C. Dodds for [How to Contribute to an Open Source Project on GitHub](https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github)!

Add Contributing md file 

---

CONTRIBUTING.md
EXAMPLE.ENV

Issue: #45
Enhancements to contributing file.
* Added EXAMPLE.ENV file
* Added link to the group's meetup 🫢 and included meeting info
I didn't update the original PR because I thought it would trigger a re-review...then am now realizing I'm requiring a re-review doing it this way...

Contributing enhancements

---

app/components/marketing/events-section.tsx
app/routes/_index.tsx
package-lock.json
package.json
prisma/schema.prisma
prisma/seed.ts

Issue: #49
This pull request introduces data loading functionality to the EventsSection component.
Incorporating data loading into EventsSection is important for providing real-time information to users.
Key changes:
- Asynchronously fetching data from Remix's loader function
- Rendering fetched data in the EventsSection component
- Translated Figma layout into HTML and CSS structure.
- Addressed challenges related to seeding data with some relations in the Prisma models
- Resolved type issue: 'string' not assignable to 'Date'
- Added Prisma's @db.Text attribute to be able to add unlimited length text values
- To have access to newly created unique ids of groups, added a findMany query
The cards look as in the Figma design. Now, the data comes from the database instead of data stored in …

Add Data Loading Feature to EventsSection

---

.github/workflows/lint.yml
README.md
app/components/marketing/benefits-section.tsx
app/entry.client.tsx
app/entry.server.tsx
app/root.tsx
app/routes/_index.tsx
package.json
server.ts

Issue: #11 
This PR auto-format all our files and adds a new GitHub action to run ESLint as a custom validation on every `git push` in PRs.
- Ran `npm run lint:fix` locally
- Added GitHub action following [this template](https://github.com/marketplace/actions/run-eslint)
There are some pretty extensive GitHubs out there that add PR comments and allow auto-fixing. For example this one: https://github.com/marketplace/actions/lint-action.
Let's keep it simple for now and iterate!

Auto format all files and add GitHub ESLint action

---

app/modules/response/response.server.ts
app/routes/_auth.signup.tsx
package-lock.json
package.json

Issue: #26 
Add zod validation to user sign up form for more robust validation.
This PR introduces the zod validation library as a new dependency and uses the library to validate user inputs from the user sign-up form. 
Incorporating a library like zod streamlines development by helping us avoid having to write custom validation logic, which speeds up development and prevents potential bugs.
There are many other [validation libraries](https://github.com/colinhacks/zod#comparison) available, but zod currently seems to be the most widely used one that has good TypeScript support.
Zod [documentation](https://github.com/colinhacks/zod).

Add zod validation to user sign up form

---

app/components/ui/forms.tsx
app/routes/_auth.login.tsx
app/routes/_auth.signup.tsx
package-lock.json
package.json

Add additional properties to the reusable `Input` component.
We currently have two different input field stylings:
- Hidden label & centered text on Sign Up & Log In
- Label & left-aligned text on all other pages
This PR adds configuration options via props!
This PR also adds `clsx` as a dependency. `clsx` is "a tiny (234B) utility for constructing className strings conditionally.
Also serves as a [faster](https://github.com/lukeed/clsx/blob/HEAD/bench) & smaller drop-in replacement for the classnames module." - https://www.npmjs.com/package/clsx

Add props to input component

---

.github/workflows/check.yml
.github/workflows/playwright.yml
.gitignore
app/components/marketing/hero-section.tsx
app/routes/search.tsx
package-lock.json
package.json
playwright.config.ts
tests/e2e/homepage-search.spec.ts

Setting up Playwright
- Followed Playwright docs to set up Playwright, including two demo tests.
- Playwright GitHub action setup
Reference: https://playwright.dev/

Setting up Playwright

---

app/components/ui/button.tsx
app/routes/about-us.tsx
tailwind.config.ts

Designed and completed about us page with images and lorem ipsum copy

About-Us page initiated design

---

app/routes/about-us.tsx

#105
Make text more tailored instead of placeholders
also made button like to group page instead of our discord page

Better About us text

---

app/routes/groups_.$groupId.tsx
prisma/schema.prisma

adding DB support to group hero image
added in imgUrl, imgAlt and socialLinks
some fields are used in the new group page, This PR adds DB support to it.

adding image fields into do for group page

---

app/components/marketing/events-section.tsx

Replaced truncate JS function with Tailwind line-clamp

---

app/components/ui/button.tsx
stories/Button.stories.ts
stories/Button.tsx

Enhance button story with arg types

Enhance button story with arg types

---

.github/workflows/storybook.yml

Issue: #<Number>
adding permission to github workflow to deploy storybook.

added permission to github workflow

---

app/routes/events_.$eventId.tsx

added a delete button to the form in order to delete events

---

app/components/marketing/events-section.tsx
app/routes/groups.tsx

Added prefetch intent to event and group links

---

app/modules/csrf/csrf.server.ts
app/modules/session/session.server.ts
app/root.tsx
app/routes/groups_.new.tsx

Using a cookie value to secure our form submissions with a CSRF token
- [What is a CSRF token? - StackOverflow](https://stackoverflow.com/questions/5207160/what-is-a-csrf-token-what-is-its-importance-and-how-does-it-work)
- [CSRF token in Remix](https://sergiodxa.com/articles/adding-csrf-protection-to-remix)

Implement csrf token
