social-plan-it/plan-it-social-web

.gitignore
package-lock.json
package.json

Issue: N/A
Update all Remix packages to the latest version and add new metafiles generated to `.gitignore`.
Changed in `package.json`:
```
@remix-run/node: ^1.7.2 -> ^1.19.0
@remix-run/react: ^1.7.2 -> ^1.19.0
@remix-run/vercel: ^1.7.2 -> ^1.19.0
@remix-run/dev: ^1.7.2 -> ^1.19.0
@remix-run/eslint-config: ^1.7.2 -> ^1.19.0
@remix-run/serve: ^1.7.2 -> ^1.19.0
```
Added to `.gitignore`:
```
/api/metafile.css.json
/api/metafile.js.json
/api/metafile.server.json
.DS_Store
```
Our current Remix version (< 1.16.1) is not compatible with Node version >= 20. Attempting to run the project with Node >= 20 will return `TypeError: Value of "this" must be of type URLSearchParams`. This issue is also documented in the Remix repo in issue [#6118](https://github.com/remix-run/remix/issues/6118).
The …

Bump all Remix packages to the latest version

---

prisma/schema.prisma

Issue: N/A
This PR adds relationship models for user-group and user-event relationships to the `prisma.schema` file.
We have the following product requirements:
- A user should be able to create/manage groups
- A user should be able to create/edit events
- A user should be able to join groups
- A user should be able to RSVP/join events
This can be translated into relationships between the user, group, and event database tables.
- A user can have many groups.
- A group can have many users.
- A user in a group has a role, like admin or member.
- A user can RSVP to many events.
- An event can have many users.

Add user group event relationships to db schema

---

app/components/layout/top-nav.tsx

Issue: #26
Reflect the user's logged in state in the top navigation bar.
- When the user is NOT logged in, the top nav shows links to `/login` and `/signup`.
- When the user is logged in, the top nav shows a button to `/logout`.
- On mobile view, change "Sign in" to "Log in" and `/signin` to `/login`
The logout button was implemented using a `POST` request via form action rather than a `GET` request via a link. This is because Remix will not re-call our `loader` functions when we do not perform an `action` and this could potentially lead to stale data (i.e. the UI might still show the user as logged in when the user has already logged out).
https://github.com/social-plan-it/plan-it-social-web/assets/63323230/63fcb0ba-55bb-43dd-bcc1-3df1e4ecfcf4 …

Reflect the user's logged in state in top nav

---

app/components/layout/top-nav.tsx

Issue: #56 
Fixes #56, where the UI shows logged in users logging out when navigating.
The log out button currently relies on `navigation.state === 'submitting' || navigation.state === 'loading'` to determine when to show pending UI to the user. However, any navigation that calls loader functions, or submissions to other forms, will also trigger this pending UI. By checking which form action triggered the navigation (i.e. `useNavigation().formAction === '/logout'`), we can show our pending UI only if the navigation was caused by a specific form action.
The [`useFetcher`](https://remix.run/docs/en/1.19.3/hooks/use-fetcher) hook was considered, but in this case, since we are doing a navigation, it makes more sense and is simpler to use the …

Fix: UI shows logged in users logging out when navigating

---

app/components/ui/containers.tsx
app/components/ui/forms.tsx
app/routes/groups_.new.tsx
package-lock.json
package.json
tailwind.config.ts

Create reusable form input components to use on our `/groups/new` route and beyond.
The input fields on our `/groups/new` route currently have a lot of repeated code. By making reusable components for these inputs, we can reduce code verbosity, keep our design more consistent, and make it easier to update our design if needed in the future.
Changes:
- Add a new `TextArea` component.
- Add a new `Button` component.
- Use our new reusable components in the `/groups/new` form.
- Update padding on the `Card` component. This is just a stylistic change to improve the UI.
- Add [`@tailwindcss/forms`](https://github.com/tailwindlabs/tailwindcss-forms) as a new dependency. This plugin provides a basic reset for form styles to give a better base for building out our form components.

Create reusable form input components

---

app/hooks/useEvents.ts
app/hooks/useGroups.ts
app/root.tsx
app/routes/events.tsx
app/routes/groups.tsx

Issue: #50 
This is the first iteration of getting data if a user logged in. This PR adds 'useEvents' and 'useGroups' hooks to simplify data usage in app routes.
We can improve the app's performance by prefetching data and displaying it to users throughout the app.
After checking MeetUp and Eventbrite web apps, it's decided to start showing 24 events and groups to prevent data over-fetching in the future. @tonydangblog suggested using 'orderBy' in the Prisma query to filter by the freshest events and maybe groups. It was also noted that we'll need createdAt rows in the data schemas. 
https://www.prisma.io/docs/concepts/components/prisma-client/pagination
https://github.com/social-plan-it/plan-it-social-web/assets/114109736/c3d66eb0-0312-4fb9-938f-bcbadfe37c7e
- Tony Dang @tonydangblog
- …

Created hooks for getting events and groups

---

app/entry.server.tsx
package-lock.json
package.json
remix.config.js
server.ts

Update all our project dependencies.
The following packages were updated and future flags were removed.
```
@remix-run/node: 1.19.0 -> 2.0.0
@remix-run/react: 1.19.0 -> 2.0.0
@remix-run/dev: 1.19.0 -> 2.0.0
@remix-run/eslint-config: 1.19.0 -> 2.0.0
@remix-run/serve: 1.19.0 -> 2.0.0
```
The following packages were removed:
```
@remix-run/vercel
@vercel/node
```
...and the configurations were updated accordingly per the Remix upgrade [guide](https://remix.run/docs/en/2.0.0/start/v2#vercel-adapter):
> The `@remix-run/vercel` runtime adapter has been deprecated in favor of out of the box Vercel functionality and will be removed in Remix v2. Please update your code by removing `@remix-run/vercel` & `@vercel/node` from your `package.json`, removing your `server.js/server.ts` file, and removing …

Update Remix to v2 and other dependencies

---

app/components/layout/footer.tsx
app/components/ui/forms.tsx
app/routes/groups.tsx
app/routes/groups_.$groupId.tsx
app/routes/groups_.new.tsx

Issue: #??
Created new individual group pages, Additionally added routing between 
- groups page <-> individual group page
- groups page <-> new groups page
- footer <-> login, signup, groups
new features, who doesn't; like it? :D
- remix routing defaults to nested routing, which is a bit tricky until we figure out the syntax of it.
- the db needs a await to actually store things
elbow grease, Tony's knowledge and Google
https://remix.run/docs/en/main/file-conventions/routes#nested-urls-without-layout-nesting
main features:
https://github.com/social-plan-it/plan-it-social-web/assets/29219684/e6d21a15-25ef-42bf-a37c-81467241036a
error boundary:
https://github.com/social-plan-it/plan-it-social-web/assets/29219684/00b43f4f-629c-4f26-9b1c-b2a0256260bd
Tony Dang @tonydangblog
Elizabeth

[Groups] Implimented groups individual page and routing between them

---

.github/workflows/check.yml
README.md
app/routes/_auth.login.tsx
package-lock.json
package.json

Issue: 
- Test check.yml file for checking types within GitHub Actions. 
- Upgrading Remix 2.0.0 -> 2.1.0. It allowed to get rid of "Jsonify Type" errors. 
```
npx upgrade-remix
```
About the Remix 2.1.0 minor upgrade: https://github.com/remix-run/remix/releases
@tonydangblog, Tony Dang
@eiffelwong1, Sing Wong

Test Typecheck in GitHub action and Upgrade to Remix 2.1.0

---

app/root.tsx
app/routes/$.tsx

Issue: #69>
Created a splat route for handling all "page not found" errors. 
[Remix docs](https://remix.run/docs/en/main/guides/not-found) recommends using splat routes for this case. Moved the 404 handling logic from ErrorBoundary in root.tsx to a separate file ($.tsx) in the routes folder.
Thanks to Kent C. Dodds for the [implementation](https://github.com/kentcdodds/kentcdodds.com/blob/main/app/routes/%24.tsx).
Even with the comments, it's not fully clear why Kent uses this code:
```javascript
export default function NotFound() {
// due to the loader, this component will never be rendered, but we'll return
// the error boundary just in case.
return <ErrorBoundary />
}
```
https://github.com/social-plan-it/plan-it-social-web/assets/114109736/a10a9596-f37c-43ee-bbb6-34ec79c6e061 …

Splat route for the 404 page

---

.github/workflows/playwright.yml

moved env under `npx playwright test` in github workflows
removed github step of creating .env file
I believe that as long as the variable is in env, node doesn't need to have a .env file to access variables with `process.env` (similar to python)

Creating a .env file is not needed node to read env

---

app/components/ui/button.tsx
app/routes/about-us.tsx
app/routes/groups_.new.tsx

Issue: #88 
This PR introduces a new button component with 24 styles for consistency and easier UI development. 
Button accepts non-optional props:
- variant: primary, secondary, warm, outlined
- buttonStyle: rounded or fullyRounded
- size: small, medium, and large
There is already an exported Button function in forms.tsx. It's not used there because the new component can make code a bit cumbersome. 
@tonydangblog recommended placing the component into src/components/button.tsx. 
This component could be more customizable. For example, accept classNames and merge them with the [tailwind-merge](https://www.npmjs.com/package/tailwind-merge) package. Also, there are many other props such as icons, labels, disabled, etc...We can consider including some of them in the future. 
Some tailwind …

Reusable Button Component with Style Variants

---

.github/workflows/check.yml
package.json

After merging the previous PR, there was a warning related to the deprecation of an action. (see a picture below). It's recommended to update actions since some old versions use old versions of Node. 
Bard AI, GitHub

Change Versions of Node and Actions Checkout

---

app/components/marketing/hero-section.tsx
app/components/ui/images.tsx
app/routes/about-us.tsx
package-lock.json
package.json

@shami-dev 
adding the capability of responsive images to our code base
this feature is only enabled on limited images for testing, will expand it once it's confirmed functioning
installed unpic
impimented in Image class under UI
edited all image that uses the class mentioned above
old image element:
new image element:
new image element with priority:
the functionality of conversion to webp cannot be verified before deployment
kinda hard to verify functionality locally (because it optimize with CDN)
https://unpic.pics/blog/responsive-images-on-remix/

adding unpic

---

app/components/layout/top-nav.tsx
app/root.tsx

adding skip to content button for keyboard-only navigation
great for accessibility in-line with w3 Bypass Blocks guidelines
https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-skip.html
downside of existing implementation additional page load is conducted, (also adds unnecessary entry to history, which makes back to last page more annoying)
reddit.com and linkedin.com have a way to not append `#main` into the URL, unable to reverse engineer what they did

add skip to content button

---

app/components/layout/footer.tsx

added a column for photo credits in the footer section

---

app/components/marketing/events-section.tsx
app/components/marketing/hero-section.tsx
app/routes/events.tsx

Modified sizes of event card to maintain consistent sizing. I also added a default event photo, truncated Event Description so the text doesn't over flow, and centered a couple divs in the Hero section.

Events route resizes and spacing/jonathan

---

app/components/layout/top-nav.tsx

@kwesibatchelor 
@willbeaumont 
Issue: #<Number>
https://github.com/social-plan-it/plan-it-social-web/issues/107
patch the issue where top-nav menu still showing when display goes bigger
can use Headless UI for it
https://github.com/social-plan-it/plan-it-social-web/assets/29219684/b93c5fce-aede-41ab-bfe9-2fd01b36faef

patch top nav menu still showing after screen size change

---

prisma/schema.prisma
prisma/seed.ts

PR to migrate database to Supabase
PlanetScale removed its free tier. This PR updates the Prisma schema for our migration to Supabase (Postgres).
- Updates Prisma schema to run on Postgres
- Adds new `DIRECT_URL` environment variable (as suggested by Supabase, [see Prisma docs for more info](https://www.prisma.io/docs/orm/reference/prisma-schema-reference))

Migrate database to Supabase

---

.env.example
EXAMPLE.ENV
README.md
prisma/schema.prisma

Thanks @JacobBaqleh1 @kwesibatchelor for joining the session :D
new documentation for better onboarding of new contributors.
some of our docs are outdated and not obvious on how to get things set up (it's still not the best but a step on a right direction)
edited readme.md, new .env.example
some repository uses CONTRIBUTING.md for the more technical information, but I think putting everything in readme is good since the group intended to get people to code more. 
also, what's a good way to encourage design contributions?

Doc Changes for better coverage on new materials

---

app/routes/_index.tsx
app/routes/about-us.tsx
app/routes/events.tsx
app/routes/groups.tsx

added meta exports to groups, about-us, and events routes
